name: capstone-motor-visualizer

services:
  heartbeat-monitor:
    build:
      context: ..
      dockerfile: Dockerfile.dev
      args:
        USERNAME: dev
        UID: 1000
        GID: 1000
    environment:
      PYTHONPATH: /app/src
    volumes:
      - ..:/app:cached
      - visualizer-poetry-venv:/app/.venv
    command:
      - poetry
      - run
      - python
      - visualizer/heartbeat_monitor.py
      - --endpoint
      - tcp://0.0.0.0:5555
      - --bind

  order-terminal:
    build:
      context: ..
      dockerfile: Dockerfile.dev
      args:
        USERNAME: dev
        UID: 1000
        GID: 1000
    environment:
      PYTHONPATH: /app/src
    volumes:
      - ..:/app:cached
      - visualizer-poetry-venv:/app/.venv
    command:
      - sleep
      - infinity

  motor:
    build:
      context: ..
      dockerfile: Dockerfile.dev
      args:
        USERNAME: dev
        UID: 1000
        GID: 1000
    depends_on:
      - heartbeat-monitor
      - order-terminal
    environment:
      PYTHONPATH: /app/src
      MOTOR_CONFIG_PATH: /app/visualizer/config.visualizer.yml
    volumes:
      - ..:/app:cached
      - visualizer-poetry-venv:/app/.venv
    command:
      - poetry
      - run
      - python
      - -m
      - capstone_motor.main

volumes:
  visualizer-poetry-venv:
